---
title: "Definición del problema"
---
En la actualidad, Chile atraviesa un sostenido y avanzado proceso de envejecimiento poblacional que está modificando la estructura por edades de la población. Los resultados del Censo 2024 muestran que la población de 65 años y más representa el 14% de la población nacional, mientras que en 1992 era un 6,6%. En paralelo, ha disminuido el porcentaje de personas de 14 años o menos de 29,4% a 17,7% en el mismo período. Con lo anterior, el Índice de Envejecimiento muestra que por cada 100 personas de 14 años o menos hay 79 personas de 65 años o más en el país, cifra que para el año 1992 era 22,3. Adicionalmente, el 11,6% de los hogares a nivel nacional están conformados solo por personas de 65 años o más. Esta cifra era 8,3% en 1992 (INEa) [@MoscosoCuaresma] . Las nuevas proyecciones del INE indican que este proceso seguirá profundizándose en las próximas décadas, de manera que para 2045, la población de 65 años y más triplicaría a la población menor de 15 años (INE,2024b).

Este proceso plantea interrogantes y desafíos respecto de las demandas futuras que podrían enfrentar las instituciones, y en particular el sistema de salud. La relación entre envejecimiento poblacional y la utilización del sistema de salud no se puede reducir a que las personas mayores utilizarán más los servicios de atención médica. Si bien la edad cronológica se relaciona con cambios en la salud, presencia de enfermedades o limitaciones funcionales, estos no se distribuyen de manera homogénea en la población, sino que están sujetos a condiciones socioeconómicas, educativas, culturales y territoriales.

Desde una perspectiva sociológica, el envejecimiento constituye, por tanto, un fenómeno que debe ser comprendido en relación con las desigualdades sociales acumuladas a lo largo de la vida. Personas de la misma edad pueden presentar diferentes condiciones de salud y distintas posibilidades de acceder a los servicios sanitarios. En este marco, el problema de investigación se sitúa en la necesidad de comprender cómo se relaciona la edad con la utilización de distintos servicios de salud en Chile y en qué medida esta relación se encuentra condicionada por las necesidades de salud y por factores sociales y estructurales que facilitan o dificultan el acceso. Comprender esta relación permite caracterizar las diferencias actuales en el uso de servicios de salud, y aproximarse a los posibles cambios futuros en la demanda sanitaria que traerá el envejecimiento poblacional.

## Objeto de estudio

El objeto de estudio corresponde a la utilización de servicios de salud en la población residente en Chile.

## Pregunta de investigación

A partir de lo anterior, se formula la siguiente pregunta de investigación:

¿Cómo se relaciona el envejecimiento con la utilización de los servicios de salud en Chile y en qué medida esta relación se modifica según las necesidades de salud y las condiciones sociales, económicas, institucionales y territoriales de las personas? 

