---
title: "Revisión inicial de literatura"
---
La investigación se sitúa inicialmente en la intersección de cuatro campos conceptuales: el envejecimiento poblacional, las desigualdades sociales en salud, las instituciones y la utilización de servicios sanitarios.

En relación al envejecimiento demográfico, este es definido como el aumento progresivo de la proporción de personas mayores, producto de la evolución conjunta de fecundidad y mortalidad [@CEPALs.f] . Desde una perspectiva individual y biológica, el envejecimiento implica cambios graduales de las capacidades físicas y mentales, y un mayor riesgo de enfermedad [@OMS2025]. Sin embargo, para esta investigación, el envejecimiento se aborda como proceso que se desarrolla a lo largo del curso de vida, por lo que la edad es una dimensión relevante pero no suficiente para explicar las diferencias en las condiciones de salud y la utilización de los servicios médicos.

En este sentido, y bajo el marco de los determinantes sociales de la salud,  se señala que las personas que logran una mejor posición social tendrán menos probabilidades de estar expuestos a enfermedades y en caso de enfermar, tendrán mejores posibilidades para afrontarlo y sufrir menores consecuencias sociales y económicas [@MoscosoCuaresma]. Por ello, las desigualdades acumuladas a lo largo del curso de vida pueden contribuir a que personas de una misma edad presenten diferentes necesidades de salud y distintas posibilidades de acceder a atención sanitaria.

Estas diferencias son relevantes al considerar el rol de las instituciones, ya que estas constituyen mecanismos desde el cual se canalizan las demandas de grupos vulnerables y se sostiene la cooperación colectiva [@Huenchuan]. En este marco, el sistema de salud representa la institución central para responder a las necesidades sanitarias de la población. Sin embargo, la forma en que se organizan y distribuyen los recursos institucionales puede contribuir a facilitar o restringir las posibilidades de acceso de distintos grupos sociales. 

Para organizar analíticamente estos factores, se utilizará el Modelo Conductual del Uso de los Servicios de Salud de Andersen, el cual sugiere que “el uso de los servicios de salud por parte de las personas depende de su predisposición a utilizarlos, así como de factores que facilitan o dificultan su uso y la necesidad de atención médica” [-@Andersen, p.651]. Para esto, desarrolla tres grupos de factores: factores predisponentes, los que corresponden a características individuales y sociales que anteceden a la utilización y que estructuran la propensión a utilizar servicios; factores facilitadores, los cuales representan recursos y condiciones que pueden permitir o dificultar la utilización; factores de necesidad que representan las condiciones que hacen necesaria o potencialmente necesaria la utilización de servicios.

